language: python

python:
  - "2.7"
  
deploy:
  provider: pypi
  user: congzhang
  password:
    secure: q5cC2aZ/W+uIWjqeYktmNzjwhRx2T7xCr/xAJaHx5cCt/6gs+fLZE9PRBhpQFm2lxxZNwcQtASJMWNF36TWjOeysmQWu76ln7eFLT71FrWVSZJRuI21Ntz4A78+1fOsNsJKFDynNun7rMLmrS+FXlaKLgjCOWbJ+T3qdlHS1uqtBEDJzvjO3ifLZSrinQfJWNzMw1BHgvJNmO0M+y8pLazC0xbx50kHirzSwN9ZjfA4Z+mwRiZpjlL5Ukd7n1b2UbiwxotDmSyZF+gQMBB7H41IgdbhzPRNKjuwhHuNxT+zktV98bYk4pekw4VRifk7/A3KzLcHkO7uPwZrAF+exLzVzQf95NLNVUFJN5xSmtIvH39DXk626D05j96/A3yvK7e4bvI01mgCSBcSZTbDKNZs1iYtRL4gO6qin+G4zJF4JPIhGHeTykDUJg52G7mIWKZci5TVnn1demgoqhrS7U2Cz62B4FNtS3RFTwQWElkw1dI+dOf8Hx+6zerkxmmpOaTITh3rgrr3mvlvMD2eRarMbcvgaWo2j49fsR4YjmIxc1LsRrg4luWr6eWrep28awpOZEkId/mms0VjKliH641zzj3OPvaa1rN2VNzo7LbKOpDZHKg+E55zMrDvXuJnLYNltW6i8CvOmuCmfCobp7rqvlTlWxOi3JzymuccbzKs=
  on:
    distributions: sdist bdist_wheel
    repo: congzhangzh/uproxy
