language: python

python:
  - "2.7"
  
deploy:
  provider: pypi
  user: congzhang
  password:
    secure: HhEqLKXSklWN2YMKL/ZYOIxcS8FqJuaqDVaOK6Gccucv4XqqCFbakmAdQizlrDjii3qYNA7YKSfzk7XsiOGhV7EF6zTlaLqIi67KxZfQf9qSatBzFl/ff/HeALn/P0lXljJBIAH0zMrNaOzE42ftDTYeMhEl/jfXKm919O9CP6AtVOz/LO0vrs0MoFSAYfqz+9ppFjlr320gOK3OxVsKtPc65SfZzfx0B44UJKuQPXIjH0oTariquoYqKIwbnnuLrVJ930s9VxdN3UgzglR6b6ZUPMgDKYBDL617/HWVK2gPnVzL9e6LjLEzzhk4IVskpnvYviH8PIwCSWYU8rTAJLwW+sByTPl3NJhWvxwd1DtpcpLDLwkiwUCN13tiK4Bsdjtr9YzXHCDksFAvjIzBtEd9TO4oTo4nqvn0EUDRSk32J1gJAOu9XGxkCPciV+JdGTtz5PUlnqknNCdaO5QaulOlcoaYoB7e8UgGpzKfc5fYsNKdsp+K8kh1WEQLcAc6rjfv91MO9w2z3O9AkUCHpny4Aq37Ea2VstOWwsUxyDL6gsOnxMnF8oqrbjZTZ2PROI88oqz7sFsuudzojgtfDJDxljTEqHb5kaT4/K+VkTkLvxUGG+KlgCUE55D2PM8VdvDgrSlpCKFVbl6sZrDZ9jXxou4SCBDUd9cp7iSdpWs=
  on:
    distributions: sdist bdist_wheel
    repo: congzhangzh/uproxy
